const GET_TOURS_LIST = 'GET_TOURS_LIST'
const GET_TOUR_BY_ID = 'GET_TOUR_BY_ID'
const GET_TOURS_BY_TAG = 'GET_TOURS_BY_TAG'
const GET_TOUR_TAGS = 'GET_TOUR_TAGS'
const GET_TOURS_BY_ID = {
    REQUEST:'GET_TOURS_BY_ID_REQUEST',
    RECEIVE:'GET_TOURS_BY_ID_RECEIVE',
    FAILURE:'GET_TOURS_BY_ID_FAILURE'
}
const FILTRATION = 'FILTRATION'
 const GET_LOCATION_BY_ID = {
    REQUEST:'GET_LOCATION_BY_ID_REQUEST',
    RECEIVE:'GET_LOCATION_BY_ID_RECEIVE',
    FAILURE:'GET_LOCATION_BY_ID_FAILURE'
}

export {
    FILTRATION,
    GET_TOURS_LIST,
    GET_TOURS_BY_ID,
    GET_TOUR_BY_ID,
    GET_LOCATION_BY_ID,
    GET_TOURS_BY_TAG,
    GET_TOUR_TAGS
}