const GET_TOURS_LIST = 'GET_TOURS_LIST'
const GET_TOUR_BY_ID = 'GET_TOUR_BY_ID'
const GET_TOURS_BY_ID = {
    REQUEST:'GET_TOURS_BY_ID_REQUEST',
    RECEIVE:'GET_TOURS_BY_ID_RECEIVE',
    FAILURE:'GET_TOURS_BY_ID_FAILURE'
}

export {
    GET_TOURS_LIST,
    GET_TOURS_BY_ID,
    GET_TOUR_BY_ID
}